### PR TITLE
Fixed folder name

### PR DESCRIPTION
**Pull request by federicomarini**

### CODE REVIEW

**Comment by LuckyMD** [comment]
thanks!

**Comment by federicomarini** [comment]
Unrelated to this PR but more to the manuscript itself:
should the x axis label of Fig 2B read "Number of genes detected", rather than "count depth"?

Once again: thanks for the excellent writeup!

**Comment by LuckyMD** [comment]
It should indeed. I didn't catch this in the proofs. It was correct in the initial submission.

**Comment by federicomarini** [comment]
Oh bummer. Hopefully they'll be able to fix it for you!

**Comment by LuckyMD** [comment]
The figure is fixed now and will be in an updated version soon. Thanks again for pointing this out!

**Comment by federicomarini** [comment]
Well thank you for following up (and to the responsive journal!)

**Comment by federicomarini** [comment]
BTW: why I was so interested in retrieving the dataset & co., is that I was trying to setup a showcase instance of iSEE here -> https://github.com/federicomarini/iSEE_instances/blob/master/iSEE_sctutorial/iSEE_sctutorial.Rmd, where I wanted to mirror the findings/highlighted points in the original paper and in your reanalysis, in a way that can be digested in iSEE (which I co-developed with other persons).
Can be something interesting for you as well - although you might be more Scanpy/python-centered?

**Comment by LuckyMD** [comment]
I am indeed more python-centered. But this is very interesting. We're looking at a few good examples for how to nicely combine R and python tools via `anndata2ri` and Seurat's `convert` function. Shiny-based GUIs like iSEE are definitely a strong case study for moving to R. That's still largely missing in python.

**Comment by federicomarini** [comment]
I do not have a strong background in Python, but do look with interest at all these "interfacing".
Especially in single cell data, there seems to be some room for improvement in (trying to) define a standard - can't avoid thinking of https://xkcd.com/927/

I'd say we can definitely catch up via email if you want - you can find me at marinif@uni-mainz.de

**Pull request merged**
